# Generated by Django 4.2.11 on 2024-11-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('content', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('escolha_unica', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['content'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostaTexto', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('respondido', models.IntegerField(default=0)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem')),
            ],
            options={
                'ordering': ['respostaTexto'],
            },
        ),
        migrations.CreateModel(
            name='Commentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem')),
            ],
            options={
                'ordering': ['postagem'],
            },
        ),
    ]
