# Generated by Django 5.0.3 on 2024-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='title',
            field=models.CharField(default='LoremIpsum', max_length=100),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
