# Generated by Django 5.0.3 on 2024-03-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='Music',
        ),
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
