# Generated by Django 5.0.3 on 2024-11-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postagem_title_alter_postagem_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistenciaUserPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersistenciaUserResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.respostas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
