# Generated by Django 4.2.11 on 2024-11-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_persistenciauserpostagem_persistenciauserresposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistenciauserresposta',
            name='resposta',
        ),
        migrations.AddField(
            model_name='persistenciauserresposta',
            name='postagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem'),
        ),
    ]
