# Generated by Django 5.0.3 on 2024-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_commentspostagem_postagem_user_delete_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
