# Generated by Django 4.2.11 on 2024-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_persistenciauserresposta_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistenciauserpostagem',
            name='feedback',
            field=models.BooleanField(null=True),
        ),
    ]
