# Generated by Django 5.0.3 on 2024-05-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentspostagem',
            name='user',
        ),
    ]
