# Generated by Django 5.0.3 on 2024-03-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_postagem_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='isTextQuestion',
        ),
    ]
