# Generated by Django 4.2.11 on 2024-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_commentspostagem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspostagem',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
