# Generated by Django 5.0.3 on 2024-04-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_postagem_istextquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentspostagem',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['content']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AlterField(
            model_name='commentspostagem',
            name='postagem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem'),
        ),
        migrations.AlterField(
            model_name='commentspostagem',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='commentspostagem',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='dislikes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='passWord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
