# Generated by Django 4.2.11 on 2024-11-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_persistenciauserpostagem_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistenciauserpostagem',
            name='feedback',
        ),
        migrations.AddField(
            model_name='persistenciauserpostagem',
            name='dislike',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='persistenciauserpostagem',
            name='like',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
