# Generated by Django 5.0.3 on 2024-04-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_commentspostagem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentspostagem',
            options={'ordering': ['text']},
        ),
    ]
