# Generated by Django 5.0.3 on 2024-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_persistenciauserpostagem_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persistenciauserpostagem',
            old_name='dislike',
            new_name='habilitado',
        ),
        migrations.RemoveField(
            model_name='persistenciauserpostagem',
            name='like',
        ),
        migrations.AddField(
            model_name='persistenciauserpostagem',
            name='tipoBotao',
            field=models.BooleanField(null=True),
        ),
    ]
