# Generated by Django 5.0.3 on 2024-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_commentspostagem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentspostagem',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
