# Generated by Django 5.0.3 on 2024-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_commentspostagem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passWord',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
