# Generated by Django 5.0.3 on 2024-12-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_dislike_persistenciauserpostagem_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
