# Generated by Django 5.0.3 on 2024-05-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_commentspostagem_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem')),
            ],
        ),
    ]
