# Generated by Django 4.2.11 on 2024-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_respostas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='respostas',
            field=models.ManyToManyField(blank=True, to='myapp.respostas'),
        ),
    ]
