# Generated by Django 4.2.11 on 2024-05-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_postagem_respostas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='respostas',
        ),
    ]
