# Generated by Django 4.2.11 on 2024-05-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_postagem_respostas'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='postagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem'),
        ),
    ]
