# Generated by Django 4.2.11 on 2024-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_respostas_postagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='postagem',
        ),
        migrations.AddField(
            model_name='postagem',
            name='respostas',
            field=models.ManyToManyField(blank=True, default='', to='myapp.respostas'),
        ),
    ]
