# Generated by Django 4.2.11 on 2024-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_respostas_postagem_postagem_respostas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='respostas',
            field=models.ManyToManyField(blank=True, to='myapp.respostas'),
        ),
    ]
