# Generated by Django 4.2.11 on 2024-05-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_postagem_respostas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(blank=True, default=[], null=True, upload_to=''),
        ),
    ]
