# Generated by Django 4.2.11 on 2024-05-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_postagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='respostas',
            field=models.ManyToManyField(blank=True, default=None, to='myapp.respostas'),
        ),
    ]
