# Generated by Django 5.0.3 on 2024-05-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_respostas_options_respostas_respostabool'),
        ('myapp', '0018_alter_postagem_respostas'),
    ]

    operations = [
    ]
