# Generated by Django 5.0.3 on 2024-05-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_merge_20240514_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostas',
            options={'ordering': ['respostaTexto']},
        ),
    ]
