# Generated by Django 5.0.3 on 2024-05-14 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_respostas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='respostas',
        ),
        migrations.AddField(
            model_name='respostas',
            name='postagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem'),
        ),
    ]
