# Generated by Django 5.0.3 on 2024-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_postagem_respostas_respostas_postagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='postagem',
        ),
        migrations.AddField(
            model_name='postagem',
            name='respostas',
            field=models.ManyToManyField(blank=True, default='', to='myapp.respostas'),
        ),
    ]
