# Generated by Django 5.0.3 on 2024-05-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_respostas_postagem_postagem_respostas'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='escolha_unica',
            field=models.BooleanField(default=False),
        ),
    ]
