# Generated by Django 5.0.3 on 2024-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_postagem_escolha_unica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='respostaBool',
        ),
        migrations.AddField(
            model_name='respostas',
            name='respondido',
            field=models.IntegerField(default=0),
        ),
    ]
