
# Generated by Django 5.0.3 on 2024-09-24 15:31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_respostas_respostabool_respostas_respondido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(blank=True, default='', null=True, upload_to='./myapp/images/'),

        ),
    ]
