<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-09-27 13:11
=======
# Generated by Django 5.0.3 on 2024-09-24 15:31
>>>>>>> 5162e3c3519f8308d54576a20aab54aa5f10ca07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_respostas_respostabool_respostas_respondido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
<<<<<<< HEAD
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
=======
            field=models.FileField(blank=True, default='', null=True, upload_to='./myapp/images/'),
>>>>>>> 5162e3c3519f8308d54576a20aab54aa5f10ca07
        ),
    ]
