# Generated by Django 5.0.3 on 2024-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_postagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='arquivo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
